language: java
jdk:
  - oraclejdk7
before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn verify -B -q
after_success: mvn coveralls:report -DjacocoReports=target/site/jacoco-ut/jacoco.xml,target/site/jacoco-it/jacoco.xml -DrepoToken=$coverallToken
