language: java
sudo: required
jdk:
  - oraclejdk7
before_install: sudo apt-get install xorg openbox; startx;
install: true
script: mvn verify -B -q
after_success: mvn coveralls:report -DjacocoReports=target/site/jacoco-ut/jacoco.xml,target/site/jacoco-it/jacoco.xml -DrepoToken=$coverallToken
