language: java
sudo: required
jdk:
  - oraclejdk7
before_install: sudo apt-get install xorg openbox 
install: true
script: mvn test -B -q
after_success: mvn coveralls:report -DjacocoReports=target/site/jacoco-ut/jacoco.xml -DrepoToken=$coverallToken
